language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
script:
- grunt && npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: OHxUFmPe/+ZCuVsRoFnQ5SovPbVY71vPLXfigNGTvln0SNaSzAxIVowuL0OKSSHMSlPDRgCoMNlHpbLgZuHo6iyRFiMG9xui2+e6HMe7lln7wV6y0eeFhJS4gxPFRQ9hUVEY/DUnMab7PNXiumuPUwY2B1WPNQs6bUBBTFmWI44zxQRWmYVtzY62yDBIj5CUNyH+l7tnqq37wqSQgNVAxID741nGkCnRinnFIJaPyXUjUbOaWCdaJ5cvRV+nmjOzaD/0Hvx4+Zh+fk/bViHNANzhFnZTB130I0Zv6GtpWGE4XGcKWWfgWiej28Z83+Qw39sl542kdjm/9Mz82N6tZO6OyQDbwxvcVpIkDftqDine1cGi6GeAXdt/nbmJxzQvj7vlpx2KMq07UW80m5XWQgl/Dda1g9L0mcVHTQNVmSv0ZBFLQF8ZKBKWEZ2mwrd1qWTFnd5fzTzfOC+x8oP8b2VdPBqjqJ7xgKXyktDIIwwMRTSrnpjkaspAN8Xrv1KNBYi9qsyGNW5F5d/dAid5jv4SjjeCmGzrN/u03HK1eLfCzdG9co2lGE3wtKi+bLR9Mbv6eh3I78o9ymZNw+stIj+ad5kO1HXMtVIFZZEK2E7MDFDYhUxCZTqqVXe6djUSZBTWSy2e7f5133f/ucWub8Cz16ayWc8Wjg/FEiMzQww=
  on:
    branch: master
    repo: kuzzleio/kuzzle-plugin-socketio
