language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
script:
- grunt && npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: XwqpPUAFl7lWTwFHnsUHvsdoYIMi1RWWlchll1WPRU3iWF9iWOzrCfpZeXs2Ma+bQfJbdZsBySL+oVaI/BVEkKWiiWEuBSLgFfl6AAT74ytexFEbUyIXkdtiXic6GDfIoR90ZBiQLXs9pRaCOZpyfI5L3KEeOkPe0MoxXD8sZbF3tfIhRoKtDruMInUrQ+OtS0uugQkAUP+Stck6RIj/xrHj6XXtMESZBP+aBxgLKeJ7ruP1zg37Fsy5HJIvN4Dcr+bM5VMbShUbNdO/mYQD2ity7EAJQRnNvYguDt8KyQSac/WhhKUHS7OtY+/iAwssC2hF1li7eAYbMifqkph2R38VZ32hXTUxL6E2BE0rO1dvOpBi65yszupoHhalQUb8OxL6Y7MismYJeVg4vLEPA/gLY9/9LMo015DKt9TwIQY6226nd/CcnGx+QAJ/Qr/vbJFCIf9S9TAJ1ptLsNrV8l2t9alqWTWX4pAOUnM80tp0XyatkyYIK55X6LgtqQZSYmRr0ECFJwnkfxbqRJeEH/5IUwn+aEIegs5pu5CazPHoNVzjlCb+/+iBjI0N2Bdwp2HMkMVgxH6itMb6ZUiIOCc8J/15rzE9cd3rrRkM8Rvu2jwx9J6tYw85u5WfsDJkoZuJL+pijybiY+HU5FFnmncrrYKiakZ/1kI7qv+77Z8=
  on:
    branch: master
    repo: kuzzleio/kuzzle-plugin-socketio
