language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
script:
- grunt && npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: XiaG89EYG6gNeAhA/5cuaqgmhX5CHLnTFqa6KL9FCFDQJPKcd9tvL9RGHaGN7FNMKYnCEaFcNDY7PYC3uuIKErpdFgopP0v6ok2E4ZAEJ67epioTwmzhZE5G1f3ll+4ppQpTAsqlTLgiSxLHiF5+bfIyK0WyN2htOm15lC15q1IoXSG3XlYad4is/rOz1EhcNsdwrKQoEIEXWe5TTDF5wMk+1JGNQ7Pu4cfdM0RMZ5ygwWOh15bT2wnBpy1beiU1oS1Sx80uBtncna0QVKXFOPYLavcOdA9fw0NSckoezhbFYTtUZUc9PaiMTZa6owArU665tEW6RDWCxGzuxayEVAqA9tZKGgfwh/iMiqOe5aioF0u4GZUipldnqBVYxdE/oMkadgPg8ltP2xlW4YTvJQkFeCOzO4vi28BHlat4xLkawD/hyxtZ8H9VUfu0+IBj18GuGw/Hg5+rHJDEDEu0LZadJD8oXrHgMTkZsog2Yq5IlJdLTLBLFaCvv3CxQns2NMop2O5Obsi4eeKL/XNsGdhK+hPFKd//r8PhMupCRsa6cYBZyPwES/cFXYQVT4jTGQhfzAfI1obTZaSpa8mJJQ3z8fpyHbyEtATW6S9ejeth8cRD6MDeWREXMEEkddKE0dRX4yNw9gJag04j+qhX3aCA4YrqVRs63kQW+16Dz0s=
  on:
    branch: master
    repo: kuzzleio/kuzzle-plugin-socketio
