language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
script:
- grunt && npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: H/FnSO+682IrWY3oLnoA8x4MVQPcNH31MrzNev2fydl67UVYD82YOnhYOlKH6t9HpQWOU0h2IJkHWpKieO6Vm9bwDN12nb/B2p6J4nMLLijCnVI6O+N8Jx0236i2+5KSeGteuv8bCgCE8DJLYV8N0Vt6ZvTmtcjFpwKQXjK8Uk8QVV3vRk921EgUBlQBVjUP9OxgUxkoxQGyPM66ZSuaMTgQ6Cgpw9XERM/iBoafICr6vPioCdzoHbEyUiqLde/1gA89nes7sdgdFtayB2n0OvnlHdeWr28/nKSOiTgBHnFN8lQFTqx6s/eZ7F7UnCml8jmXmzRZ3MMI0k3drsSCXD2FRcSvPhrLvCu16kVQqnHT27w+wCmI26ifdMepfKyUydM9eYqj7VO3EJqB3zv6dHVVx/SHuX17/+BXsyIApYrt6jcjIIj5dKlDXgkXZ+dtcy6j/RQY92FG/VtPKyTiErT4ekwa1UpiXVDwR6cZuLOiS4Xux7yolXY+AhRZxiZHhLt7UQGJaxPBwbkNX0A1DIPzZXz+IG3p4iPw3x4cIVULMqp0fqzVyw/YE7PUpkss29YxstJGfvmF7pCxlbYmMbIcCOAGZEaJfrS8TSbr/DIymACT3fTlHXXJgF84ISKQixPk2iZSCWFfaHwxZ1coDpIKpVMzKHNwLqoCmD1j+Js=
  on:
    branch: master
    repo: kuzzleio/kuzzle-plugin-socketio
env:
  global:
    secure: QMac51L2Zolu9IzYEIw1XJkANxM73OxCGWT9egbQSSSZgGrrjAO53WJy1u4jo5rIcoxL5pBSwU1d2wnx3Wb00X43egSY9npuli3MYwE3t0rREqehYistYvzBWS1V96/PpqWaWAYcCS/kIrrdpXXN/7KLoH2K/1GStOyvCQ5GvLSUTg0ANCTJ/ZqwFFGP/HGcqCkQBKbkLUgae/jwdlEAzrl2MNTzhehGga1mSNvoS+eVfwHj0ZGsW6z/UpM7jF19llHN/K9dDpQVTPfVyyhZ4UixFja0kHdWAwlYhK+RRPIFE/jtkB5LVeRZVjHNr+bCYcZlPjmTQt1fiw1M28Ii89SCG/neK4Y2D2BEHuumSddCiTafZT57KHVTNl+Axp+u4LUleb4IKZEDv6f7XV324G+hvQkOxVprLwbeKYGiGDueZe7Slgr9KVvQNcMgIzLMgpEiRPpj6p8aReVgKyqvpljXKOoFqob9dXbuiSOG4x8YUk7em64ruBaERIU4fSoSkPMDikNc/Goj3s033VzwayZUT0TYV6XMc9S7LoKw0kGckas5aja8JB1EiZcekiKM5VwHUSJAdX6ZDuj2prOrQVvZI8xG9QfgERti1VMT7gnQnFbvOQ56wk8nDvvJxdPcHthqRHjpZl91nycV0XL/U/JZaBRMKF0kFANVcg3lyOI=
